services:
  # Backend Service
  - type: web
    name: lumio-backend
    env: node
    plan: free
    buildCommand: cd backend && npm ci && npx prisma generate && npx prisma db push
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: lumio-database
          property: connectionString
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
    autoDeploy: false

  # Frontend Service
  - type: web
    name: lumio-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm ci && npm run build
    staticPublishPath: frontend/dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_API_URL
        value: https://lumio-backend.onrender.com
    autoDeploy: false

databases:
  - name: lumio-database
    databaseName: lumio
    plan: free
